name: $pluginName
version: $pluginVersion
main: $pluginMain
api-version: 1.16
authors: [ TeamVery ]
website: https://github.com/TeamVery/config-framework-sample

commands:
  reload:
    permission: op
    description: Reload Configs