name: Config-Framework-Sample
version: @version@
main: com.teamvery.configframeworksample.ConfigFrameworkSample
api-version: 1.16
authors: [ TeamVery ]
website: https://github.com/TeamVery/config-framework-sample
